name: Deploy to gh-pages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Build static pages
        run: |
          npm run build
          touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
